
name: .NET Core Desktop

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    strategy:
      matrix:
        configuration: [Debug]

    runs-on: windows-latest  # For a list of available runner types, refer to
                             # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idruns-on

    env:
      Solution_Name: MyArchive.sln                        # Replace with your solution name, i.e. MyWpfApp.sln.
      Main_Project_Path: MyArchive.csproj

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Install the .NET Core workload
    - name: Install .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    # Add  MSBuild to the PATH: https://github.com/microsoft/setup-msbuild
    - name: Setup MSBuild.exe
      uses: microsoft/setup-msbuild@v2

    # Execute all unit tests in the solution
    - name: Execute unit tests
      run: dotnet test

    - name: Restore
      run: msbuild $env:Solution_Name /t:Restore /p:Configuration=${{ matrix.configuration }} /p:Platform="x64"

    - name: Build Solution
      run: msbuild $env:Solution_Name /p:Configuration=${{ matrix.configuration }} /p:Platform="x64" /p:RuntimeIdentifier=$env:Runtime_Identifier

    - name: Publish Main Project
      run: dotnet publish $env:Main_Project_Path --configuration ${{ matrix.configuration }} --output ./publish --runtime $env:Runtime_Identifier --no-build --self-contained false


        
  Deploy:
    needs: build
    runs-on: windows-latest
    steps:
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-artifact
          path: publish
